### ISSUE TITLE
Nordic License

### ISSUE THREAD

**Issue by mrquincle** [mbedmicro/nRF51822#1]
Hi guys,

Honestly, I don't see how you guys honor the copyright statement from Nordic in the implementation of their softdevice: https://github.com/mbedmicro/nRF51822/tree/master/nordic/ble

```
/* Copyright (c) 2012 Nordic Semiconductor. All Rights Reserved.
 *
 * The information contained herein is property of Nordic Semiconductor ASA.
 * Terms and conditions of usage are described in detail in NORDIC
 * SEMICONDUCTOR STANDARD SOFTWARE LICENSE AGREEMENT.
 *
 * Licensees are granted free, non-transferable use of the information. NO
 * WARRANTY of ANY KIND is provided. This heading must NOT be removed from
 * the file.
 *
 */
```

The use is non-transferable. Do you have a special agreement with Nordic about the use in mbed?

**Comment by rgrover** [comment]
Nordic has acknowledged that use of their code by mbed is not an issue. They have agreed to work on a new license for their upcoming SDK. This is expected to update the license headers towards the beginning of February.

**Comment by mrquincle** [comment]
Nice!

**Comment by wolfeidau** [comment]
This is great news, as a user of nordic and mbed I am looking forward to hearing more!

Thanks for posting this.

**Comment by rgrover** [comment]
Nordic’s BLE stack is all in binary. This is their main IP. It gets merged with the application by our toolchain. It comes with the obvious restrictions that their stack should only be used for Nordic-hardware and should not be reverse engineered.

They supply some headers and example code to allow their customers to interface with the stack. They call this their SDK. The headers define the API into the BLE stack. Their SDK headers come with the following BSD-like license.

/*
* Copyright (c) Nordic Semiconductor ASA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification,
* are permitted provided that the following conditions are met:
*
*   1. Redistributions of source code must retain the above copyright notice, this
*   list of conditions and the following disclaimer.
*
*   2. Redistributions in binary form must reproduce the above copyright notice, this
*   list of conditions and the following disclaimer in the documentation and/or
*   other materials provided with the distribution.
*
*   3. Neither the name of Nordic Semiconductor ASA nor the names of other
*   contributors to this software may be used to endorse or promote products
*   derived from this software without specific prior written permission.
*
*   4. This software must only be used in a processor manufactured by Nordic
*   Semiconductor ASA, or in a processor manufactured by a third party that
*   is used in combination with a processor manufactured by Nordic Semiconductor.
*
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
* ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
* ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/

Within the Nordic SDK, there are some helper component libraries to support common operations such as access to internal flash or for features around firmware-update. This supporting functionality comes with the following license header:

/* Copyright (c) 2013 Nordic Semiconductor. All Rights Reserved.
*
* The information contained herein is property of Nordic Semiconductor ASA.
* Terms and conditions of usage are described in detail in NORDIC
* SEMICONDUCTOR STANDARD SOFTWARE LICENSE AGREEMENT.
*
* Licensees are granted free, non-transferable use of the information. NO
* WARRANTY of ANY KIND is provided. This heading must NOT be removed from
* the file.
*
*/

So, whilst the stack API headers have BSD-like license, the license for supporting code is ambiguous (and states that it is non-transferable). We do use some of this supporting code.

I’ll try to get further clarification from Nordic.
